name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: cml_run        
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "MODEL METRICS"
          cat metrics.txt
